### ISSUE TITLE
Keil Studio Cloud BUILD problem

### ISSUE THREAD

**Issue by mesut92** [Arm-Examples/mlek-cmsis-pack-examples#2]
Hi 
I was using Keil Cloud before. And i can get BUILD successfully. But when i try it now, it produces 5 MB .axf file, instead of .bin file. SO I can not use it  in STM Card? What is the problem, I could not fix it?

BR

**Comment by Burton2000** [comment]
Hi,
We have just recently pushed some updates to support CMSIS-toolbox 2.0 in this project, which is needed for latest versions of Keil Studio Cloud. These changes likely broke things for you unfortunately.

The latest merge today fixed things up so that everything should build for all targets when using CMSIS-toolbox 2.0. However, for KSC there is a bug that prevents you building correctly for all targets, the fix for this is now available for CMSIS csolution VSCode extensions and should be in the next release of KSC, so until that gets released KSC builds will not work correctly. 

Best regards,
Richard

**Comment by mesut92** [comment]
Hi Richard
In VS, I cloned the repo. And build the project. Still it did not generate .bin file, it generated .axf file.

**Comment by Burton2000** [comment]
Ah yep I understand the issue now. Looks like we were getting these all by default and now it might need to be specified.

Can you try adding the following:

```
output:
  type:
    - elf
    - bin
 ```

to [this line](https://github.com/Arm-Examples/mlek-cmsis-pack-examples/blob/38db9fe2ddc9d15b6bafff7a8ef97062515ba9d5/kws/kws.cproject.yml#L20).

So it will look like:

```
project:
  output:
    type:
      - elf
      - bin

  groups:
    ...
 ```

This generates me the bin file as well.

**Comment by mesut92** [comment]
Thanks, that fixed.

**Comment by Burton2000** [comment]
Thanks for confirming it's fixed, ill make this change upstream as well then. Also KSC was updated and should now work again for builds.
